name:                pantomime-clash
version:             0.1.0.0
github:              "githubuser/pantomime-clash"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2026 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pantomime-clash#readme>

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- ConstraintKinds
- DataKinds
- DeriveDataTypeable
- DeriveTraversable
- FlexibleContexts
- FlexibleInstances
- GADTs
- ImportQualifiedPost
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeAbstractions
- TypeApplications
- TypeFamilies
- TypeOperators

dependencies:
- base >= 4.7 && < 5
- clash-prelude
- composition
- constraints
- pantomime

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
